const requestJson = require('./request.json')

// ------------------------------------------------
// code generated by Postman (https://postman.com/)
// ------------------------------------------------

var myHeaders = new Headers();
myHeaders.append("Content-Type", "application/json");

var raw = JSON.stringify(requestJson);

var requestOptions = {
  method: 'POST',
  headers: myHeaders,
  body: raw,
  redirect: 'follow'
};

fetch("https://scanner.tradingview.com/crypto/scan", requestOptions)
  .then(response => response.text())
  .then(result => console.log(result))
  .catch(error => console.log('error', error));